### ISSUE TITLE
Overlay during entropy generation

### ISSUE THREAD

**Issue by checksum0** [theantnest/bccaddress#16]
The green bitcoin cash logo prevent someone from clicking anywhere during entropy generation, which force someone for finish generating entropy before being able to click away on another language. 

Not good for non-english speaker that don't get what is going on/required of them and just want to change language to get the explaination.

Tested on Chrome+Firefox (both latest) on Windows 7.

**Comment by zquestz** [comment]
Hmm I do not have that issue. I am able to click the other languages, I do agree it is a bit tricker, as sometimes it gets in the way. Should we remove it? What do you think is the best way to resolve it?

**Comment by theantnest** [comment]
Yes, this is noted, however there is another bug from the source code, which switches the language back to English immediately after the entropy generation anyway lol.

**Comment by theantnest** [comment]
So pick your way to die

**Comment by theantnest** [comment]
Both issues now fixed.
