### ISSUE TITLE
Blockchair is not a Bitcoin Cash wallet

### ISSUE THREAD

**Issue by Har01d** [theantnest/bccaddress#21]
Hello,

In multiple languages there’s a tip that Bitcoin Cash can be spent using Blockchair.com, e.g.:

`singletip5": "<b>Spend your bitcoins</b> by going to https://blockchair.com/bitcoin-cash/blocks and sweep the full balance of your private key into your account at their website. You can also spend your funds by downloading one of the popular bitcoin p2p clients and importing your private key to the p2p client wallet. Keep in mind when you import your single key to a bitcoin p2p client and spend funds your key will be bundled with other private keys in the p2p client wallet. When you perform a transaction your change will be sent to another bitcoin address within the p2p client wallet. You must then backup the p2p client wallet and keep it safe as your remaining bitcoins will be stored there. Satoshi advised that one should never delete a wallet.”`

This is however misleading, since Blockchair is a search and analytics system (blockchain explorer) for Bitcoin and Bitcoin Cash, we do not provide wallet services. I’d suggest changing the link to https://www.bitcoincash.org/#wallets to avoid confusion.

Thank you!

**Comment by zquestz** [comment]
Thank you for pointing this out. Will fix. =)

**Comment by zquestz** [comment]
Fixed and posted.
