### ISSUE TITLE
Cashaddress prefix

### ISSUE THREAD

**Issue by CreativeName4** [theantnest/bccaddress#22]
Hi Guys, really hope I'm doing this in the right place.. apologies if im not!

We are trying to use cashaddress more frequently to onboard new comers to BCH, there is 1 issue and 1 request here.

Issue: most wallets do not yet support the cashaddress prefix, can we have an option to toggle that off until they do? for example, bitcoin.com wallet can not sweep a cashaddress wallet at the moment.

Request: Can we have a few different options for background graphics for the paper wallet? would be nice to have a few options, especially with the holidays coming up! :)

You guys rock!!

**Comment by zquestz** [comment]
So, I would like to keep the prefix. This is being used to guarantee it scans into the correct wallet. Most wallets have already updated to include this (ABC, Unit, Stash, etc). Ideally that support should be added to the bitcoin.com wallet, as it is a tiny change.

Unfortunately it's harder than it seems for us to add that toggle, as it changes the size of the QR codes that are generated, and throws off the layout considerably.

As for the additional artwork, I am sure that is something we could add. @theantnest how do you feel about that?

**Comment by CreativeName4** [comment]
totally understand on the toggle prefix. 

as for the graphics.. yes please!!

**Comment by checksum0** [comment]
I also support pushing for wallet to support the spec as they are tbe one lagging behind, as discussed on slack.

**Comment by zquestz** [comment]
Closing as this is better fixed by the wallet.
