### ISSUE TITLE
Printing a wallet results in mess

### ISSUE THREAD

**Issue by rnkn** [theantnest/bccaddress#23]
Creating a “Single Wallet” the clicking Print creates a mess. The `div#singlesafety` overlaps the private key. See attached PDF.

[printwallet.pdf](https://github.com/theantnest/bccaddress/files/1546419/printwallet.pdf)

To correct this, do not use `height` CSS on `#keyarea` or `.keyarea`.

**Comment by zquestz** [comment]
Feel free to submit a PR to fix the issue! Generally people print the actual paper wallets and not the home page. =)

**Comment by rnkn** [comment]
I think this highlights another issue though, which is that it is likely confusing to newcomers to differentiate between a "single wallet" and a "paper wallet" when these are effectively the same. I've never actually seen people use the fancy paper wallet style (although I have seen these for sale, pre-generated, on eBay).
