### ISSUE TITLE
Add support for new cashaddr format!

### ISSUE THREAD

**Issue by zquestz** [theantnest/bccaddress#24]
If anyone wants to update code for the new cashaddr format that would be epic. Otherwise I will try to get to it soon. =)

**Comment by DesWurstes** [comment]
If you need, I have a one-file, dependencyless address translator here: https://github.com/cashaddress/cashaddress.github.io/blob/master/main.js

**Comment by zquestz** [comment]
This is now up for  review -> https://github.com/theantnest/bccaddress/pull/26

**Comment by zquestz** [comment]
Done
