### ISSUE TITLE
Generate paper wallet in other language?

### ISSUE THREAD

**Issue by ftrader** [theantnest/bccaddress#29]
I love the findbitcoin.cash idea and think it would be very helpful if the generated paper wallets were available in other languages. I see this as a 3 step process:

1. make the generation process generic enough to handle other languages on the paper wallet
2. do the actual translations for the existing languages which are on the website's generation page, and make sure that a language is used if it is available, otherwise fall back to English
3. add more languages

I would like to organize a bounty for someone who can do (1). It would be helpful to know how much effort would be required to produce a good solution for it. Excluding the work needed for the actual translation.

**Comment by zquestz** [comment]
Sorry, haven't looked at this repo in a while. It would be great to get this done! Unfortunately lots of the content is in the graphics themselves, so we would need an artist to make updated versions in all supported languages.
