### ISSUE TITLE
Checksums

### ISSUE THREAD

**Issue by sinbik** [theantnest/bccaddress#31]
Thanks you guys for nice generator. Where can I find checksums ?

**Comment by sinbik** [comment]
@GitCash 10 bits for @theantnest

**Comment by GitCash** [comment]
Hey **theantnest**, user **sinbik** tipped you **10 bits** in Bitcoin Cash ( ~ **$0.0051** ).

*[Click here to claim it!](https://gitcash.io/claim/theantnest)*

You can also add the "thumbs down" reaction to **sinbik**'s comment above to prevent future tips.

**Comment by wattans** [comment]
...

**Comment by wattans** [comment]
wattans

**Comment by Binh0103** [comment]
https://github.com/theantnest/bccaddress/issues/27#issue-292260293

**Comment by Adamkowboy1984** [comment]
How do I get a bch
